#!/usr/bin/env bash
# A script displays 'To infinity and beyond' indefinitely
# requirement: in between each iteration of loop, add sleep 2

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done