#!/usr/bin/env bash
# displays "bad luck" 4th line "good luck" 8th and "Best School" for the rest
i=1
while ((i<11))
do
	if ((i==4))
	then
		echo "bad luck"
	elif ((i==8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i+=1))
done